version: '3.8'
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo_data:/data/db
  api:
    build: .
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb
    depends_on:
      - mongo
volumes:
  mongo_data: